### ISSUE TITLE
Exception when adding item on empty container

### ISSUE THREAD

**Issue by jvalenciag** [tyl/mongodbcontainer-addon#13]
When addItem(item) is called in a empty container yields this exception:
java.lang.ArrayIndexOutOfBoundsException: 0
    at org.tylproject.vaadin.addon.utils.Page.set(Page.java:61)
    at org.tylproject.vaadin.addon.MongoContainer.fetchPage(MongoContainer.java:362)
    at org.tylproject.vaadin.addon.MongoContainer.page(MongoContainer.java:371)
    at org.tylproject.vaadin.addon.MongoContainer.refresh(MongoContainer.java:635)
    at org.tylproject.vaadin.addon.MongoContainer.addEntity(MongoContainer.java:464)

**Comment by evacchi** [comment]
Hi I have added a test case for your issue in 274a435 but I cannot seem to reproduce the problem. Which flavour of the MongoContainer are you using? Is it buffered or not? there is no `addItem(item)` (actually, there are, but they all throw UnsupportedOperationException). Are you using the latest version?

**Comment by jvalenciag** [comment]
It is not buffered, I am using the latest version, I am calling addEntity function, this happens when the Mongo  collection is empty.

**Comment by evacchi** [comment]
here's the code I'm executing:

``` java
   // BaseTest.java
    public void removeAll() {
        mongoOps.dropCollection(Customer.class);
    }


   // MongoContainerTest.java
    @Test
    public void testAddOnEmpty() {
        removeAll();

        final MongoContainer<Customer> mc = 
                MongoContainer.Builder.forEntity(beanClass,mongoOps).build();

        final Customer ljenkins = new Customer("Leroy", "Jenkins");
        mc.addEntity(ljenkins);
        assertFalse(
            mongoOps.find(
                Query.query(
                   where("firstName").is("Leroy")
                    .and("lastName") .is("Jenkins")), Customer.class).isEmpty()
        );

    }

```

this throws no error. Are you able to provide a self-contained test so I can reproduce the problem?

**Comment by evacchi** [comment]
closing; feel free to reopen in case the bug becomes reproducible.
