### ISSUE TITLE
Filtered Container returns unfiltered results, correct count.

### ISSUE THREAD

**Issue by evacchi** [tyl/mongodbcontainer-addon#3]

**Comment by ares242** [comment]
Not only in buffered container, also in non-buffered container, it returns the rigth number of items but wrong results

**Comment by evacchi** [comment]
Hi, do you have an example?

**Comment by ares242** [comment]
Yes, I have tried to use mongo container in the backend of the new vaadin-archetype-application-example. I modified to search only by the product name field using a simple string filter (test01-ui/src/main/java/com/jvg/samples/crud/ProductTable.java:120), in the images I searched for "becom" , the filter showed in the logs is jbossastest.$cmd { "count" : "product" , "query" : { "productName" : { "$regex" : ".*\\Qbecom\\E.*" , "$options" : "i"}}},.

![screenshot from 2015-01-05 20 30 37](https://cloud.githubusercontent.com/assets/2352653/5622988/d2fffd4a-9519-11e4-907d-d085798b3139.png)
![screenshot from 2015-01-05 20 31 12](https://cloud.githubusercontent.com/assets/2352653/5622989/d30304b8-9519-11e4-83e9-eb5616aad4d6.png)

Aqui esta el [codigo fuente](https://drive.google.com/file/d/0B2kL-U7RQiN-OGs3ZHhMeHZiRVE/view?usp=sharing)

**Comment by ares242** [comment]
Making some tests, I found that the container shows only the first n items, where n is the result size of the query.

**Comment by evacchi** [comment]
The bug should be now fixed in v0.9.5.5-beta. Thanks for reporting!
